begin;
select plan(18);
select has_table('private','financial_exception_cases','financial exception cases are durable');
select has_column('public','marketplace_checkouts','closed_for_new_payments_at','provider closure is recorded');
select has_column('public','marketplace_checkouts','closure_evidence','provider closure evidence is recorded');
select has_column('public','service_requests','replacement_of_request_id','replacement request lineage is recorded');
select has_function('public','request_job_cancellation',array['uuid','text','integer'],'cancellation workflow exists');
select has_function('public','request_professional_replacement',array['uuid','text','integer'],'replacement request exists');
select has_function('public','mark_marketplace_checkout_closed',array['uuid','jsonb'],'provider closure boundary exists');
select has_function('public','clear_financial_exception',array['uuid','integer','jsonb'],'finance clearance exists');
select has_function('public','resolve_financial_exception',array['uuid','integer','text'],'operations resolution exists');
select has_function('public','list_financial_exceptions',array['integer','timestamp with time zone'],'financial queue exists');
select has_function('public','get_payment_refund_execution_context',array['uuid','uuid'],'refund worker context exists');
select function_privs_are('public','request_job_cancellation',array['uuid','text','integer'],'authenticated',array['EXECUTE'],'authenticated operations boundary exists');
select function_privs_are('public','clear_financial_exception',array['uuid','integer','jsonb'],'authenticated',array['EXECUTE'],'authenticated finance boundary exists');
select function_privs_are('public','get_payment_refund_execution_context',array['uuid','uuid'],'service_role',array['EXECUTE'],'only service worker receives refund context');
select ok(not has_table_privilege('authenticated','private.financial_exception_cases','SELECT'),'private cases are not directly readable');
select has_trigger('public','jobs','marketplace_assignment_guard','financial guard remains installed');
select like((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='clear_financial_exception'),'%checkout_is_financially_closed%','finance cannot clear an open checkout');
select like((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='resolve_financial_exception'),'%replacement_of_request_id%','replacement creates linked service instead of mutating beneficiary');
select * from finish();
rollback;
