begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(18);
select has_table('private','outbox_delivery_snapshots','Delivery snapshots are private');
select ok((select relrowsecurity and relforcerowsecurity from pg_class where oid=to_regclass('private.outbox_delivery_snapshots')),'Delivery snapshots force RLS');
select ok(not has_table_privilege('service_role','private.outbox_delivery_snapshots','select'),'Service role cannot read snapshots directly');
select has_column('private','outbox_events','delivery_revision','Outbox has an operations version');
select has_column('private','outbox_events','delivery_outcome','Outbox records delivery outcome');
select has_column('public','notifications','outbox_id','In-app notifications retain the outbox identity');
select has_column('public','notifications','action_url','In-app notifications retain the authorized action URL');
select ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname in('resolve_outbox_delivery','seal_outbox_delivery','finish_in_app_delivery','finish_email_delivery','stop_outbox_delivery') and p.prosecdef),'Public worker wrappers are security invoker');
select ok(has_function_privilege('service_role','public.resolve_outbox_delivery(uuid,uuid)','execute'),'Service role can resolve a current claim');
select ok(not has_function_privilege('authenticated','public.resolve_outbox_delivery(uuid,uuid)','execute'),'Authenticated callers cannot resolve private delivery data');
select ok(not has_function_privilege('anon','public.seal_outbox_delivery(uuid,uuid,jsonb)','execute'),'Anonymous callers cannot seal delivery content');
select ok(has_function_privilege('service_role','public.claim_outbox_events(text,integer,integer,text[])','execute'),'Service role can claim enabled channels');
select ok(not has_function_privilege('authenticated','public.claim_outbox_events(text,integer,integer,text[])','execute'),'Authenticated callers cannot claim enabled channels');
select ok(has_function_privilege('authenticated','public.list_outbox_deliveries(integer,timestamptz,uuid)','execute'),'Authenticated admins can enter the protected listing workflow');
select ok(not has_function_privilege('anon','public.list_outbox_deliveries(integer,timestamptz,uuid)','execute'),'Anonymous callers cannot list delivery operations');
select ok(has_function_privilege('authenticated','public.retry_outbox_delivery(uuid,integer,text)','execute'),'Authenticated admins can enter the protected retry workflow');
select has_trigger('public','service_quotes','quote_ready_notification','Ready quotes enqueue notification intent');
select has_trigger('public','payments','payment_notification','Payment changes enqueue notification intent');
select * from finish();
rollback;
