begin;
select no_plan();
select ok(not has_column_privilege('authenticated','public.professional_invitations','token_hash','select'),'invitation token hash is not exposed to users or operators');
select ok(not has_column_privilege('authenticated','public.professional_profiles','status','update'),'professional status has no raw authenticated update grant');
select ok(not has_column_privilege('authenticated','public.professional_documents','status','update'),'document review has no raw authenticated update grant');
select ok(not has_table_privilege('authenticated','private.professional_application_submissions','select'),'submission snapshots stay private');
select ok(not has_table_privilege('service_role','private.professional_review_policies','update'),'runtime services cannot change documentary policy');
select is((select count(*) from private.professional_review_policies),0::bigint,'migrations do not invent approved documentary requirements');
select ok(not has_function_privilege('anon','public.accept_professional_invitation(text)','execute'),'anonymous visitors cannot consume invitations');
select ok(not has_function_privilege('service_role','public.accept_professional_invitation(text)','execute'),'invitation claiming requires a real session');
select ok(not has_function_privilege('anon','public.list_professional_workflow(text,integer,timestamptz,uuid)','execute'),'anonymous visitors cannot list dossiers');
select ok(not has_function_privilege('authenticated','private.professional_clearance_valid(uuid)','execute'),'clearance helper cannot enumerate another professional');
select ok(has_function_privilege('anon','public.professional_invitation_matches(text,text)','execute'),'registration can validate token and recipient without exposing identity');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='private' and p.prorettype<>'trigger'::regtype and has_function_privilege('anon',p.oid,'execute')),0::bigint,'anonymous sessions have no executable private domain function');
select ok(not has_schema_privilege('anon','private','usage'),'anonymous invitation validation preserves the private-schema boundary');
select is((select count(*) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='invitation_gateway' and has_function_privilege('anon',p.oid,'execute')),1::bigint,'the separate anonymous gateway exposes only a boolean token and recipient match');
set local role anon;
select is(public.professional_invitation_matches(repeat('a',43),'nobody@lysto.test'),false,'unknown invitation is not valid');
select is(public.professional_invitation_matches(null,null),false,'null invitation input fails closed');
select is(public.professional_invitation_matches('invalid','nobody@lysto.test'),false,'invalid token alphabet fails closed');
reset role;
set local role authenticated;
select throws_ok($$select public.list_professional_workflow('professionals')$$,'42501',null,'listing requires current operations authority');
select throws_ok($$select public.create_professional_invitation('nobody@lysto.test','aire_acondicionado','Testing denied invitation')$$,'42501',null,'inviting requires current MFA and operations authority');
select throws_ok($$select public.professional_review_context()$$,'42501',null,'unbound sessions cannot read an application');
reset role;
select * from finish();
rollback;
