begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(16);
select ok(not has_function_privilege('authenticated','public.submit_service_quote(uuid)','execute'),'Unversioned acceptance is retired');
select ok(not has_function_privilege('authenticated','private.submit_service_quote(uuid)','execute'),'Private unversioned acceptance cannot bypass the replacement');
select ok(not has_function_privilege('authenticated','public.review_service_quote(uuid,text)','execute'),'Unversioned review is retired');
select ok(not has_function_privilege('authenticated','private.review_service_quote(uuid,text)','execute'),'Private unversioned review is retired');
select ok(not has_function_privilege('authenticated','public.update_quote_policy(jsonb)','execute'),'Generic settings policy approval is retired');
select ok(not has_function_privilege('authenticated','private.update_quote_policy(jsonb)','execute'),'Private generic policy approval is retired');
select ok(not has_table_privilege('service_role','public.service_quotes','insert'),'Service role cannot insert a quote around the controlled writer');
select ok(not has_function_privilege('authenticated','public.persist_calculated_quote(uuid,uuid,uuid,jsonb)','execute'),'An authenticated client cannot forge the calculator snapshot');
select ok(not has_function_privilege('authenticated','private.persist_calculated_quote(uuid,uuid,uuid,jsonb)','execute'),'The private calculator writer remains service-only');
select ok(not has_function_privilege('anon','public.persist_calculated_quote(uuid,uuid,uuid,jsonb)','execute'),'Anonymous callers cannot write calculations');
select ok(not has_function_privilege('service_role','public.submit_service_quote_v2(uuid,integer)','execute'),'Acceptance requires the customer session, not a service key');
select ok(not has_table_privilege('authenticated','private.quote_policy_versions','insert,update,delete'),'Financial history cannot be edited directly');
select ok(not has_table_privilege('service_role','private.quote_policy_versions','insert,update,delete'),'Service credentials cannot approve a financial policy');
select ok(not has_table_privilege('authenticated','private.quote_policy_current','update'),'Only the finance workflow changes the current policy');
select ok(not has_function_privilege('authenticated','private.attach_quote_uploads(uuid,uuid)','execute'),'Photo attachment occurs only inside acceptance');
select ok(not has_function_privilege('service_role','private.attach_quote_uploads(uuid,uuid)','execute'),'Service credentials cannot attach photos around acceptance');
select * from finish();
rollback;
