begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(15);
select has_table('public','support_case_events','Support cases have one durable timeline');
select has_table('private','support_case_commands','Case intake has replay protection');
select has_column('public','complaints','assigned_to','Case owner is persisted');
select has_column('public','complaints','due_at','Operational deadline is persisted');
select has_column('public','complaints','policy_snapshot','SLA policy is captured');
select has_column('public','warranty_claims','coverage_eligible','Coverage result is persisted');
select has_column('public','warranty_claims','complaint_id','Warranty shares the support case');
select has_column('public','jobs','warranty_revisit_of_job_id','Revisit preserves original job');
select has_column('public','jobs','billing_policy','Revisit charge policy is explicit');
select ok(has_function_privilege('authenticated','public.open_support_case(uuid,text,text,boolean,boolean,boolean,uuid[],uuid)','execute'),'Authenticated intake enters guarded RPC');
select ok(has_function_privilege('authenticated','public.open_warranty_claim(uuid,text,boolean,uuid[],uuid)','execute'),'Customer warranty enters guarded RPC');
select ok(has_function_privilege('authenticated','public.update_support_case(uuid,text,integer,text,text,uuid,uuid[],text,boolean)','execute'),'Participants use guarded transitions');
select ok(not has_function_privilege('anon','public.open_support_case(uuid,text,text,boolean,boolean,boolean,uuid[],uuid)','execute'),'Anonymous intake is blocked');
select ok(not has_table_privilege('authenticated','public.complaints','insert'),'Direct case inserts are blocked');
select ok(not has_column_privilege('authenticated','public.support_case_events','internal_note','select'),'Participants cannot query private notes');
select * from finish();
rollback;
