import { test, expect } from '@playwright/test'

test('cliente puede recorrer el wizard visual de aire acondicionado', async ({ page }) => {
  await page.goto('/app/solicitar/aire-acondicionado')
  await expect(page.getByRole('heading', { name: 'Solicitar técnico de aire' })).toBeVisible()
  await expect(page.getByText('¿Qué sucede?')).toBeVisible()
  await page.getByRole('button', { name: /No enfría/ }).click()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await expect(page.getByText('Contanos un poco más')).toBeVisible()
  await page.getByRole('button', { name: /Hace días/ }).click()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await expect(page.getByText('Diagnóstico preliminar')).toBeVisible()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await expect(page.getByText('¿Dónde está el equipo?')).toBeVisible()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await expect(page.getByText('Elegí el horario')).toBeVisible()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await expect(page.getByText('Elegí tu presupuesto')).toBeVisible()
  await page.getByRole('button', { name: 'Continuar' }).click()
  await expect(page.getByText('Buscando el mejor profesional')).toBeVisible()
})
