'use client'

import { useState } from 'react'
import { auditLogs } from '@/lib/mock/lysto-data'
import { Badge, Button, DataTable, Facts, Field, Header, Metrics, Notice, Panel, useAdminDraft } from './admin-ui'

const cases = [
  { id: 'caso_001', title: 'Pérdida de agua recurrente', customer: 'Cliente de demostración', category: 'Garantía', status: 'En revisión', priority: 'Alta', detail: 'El cliente informa que la pérdida de agua reapareció 48 horas después de la visita.', next: 'Solicitar evidencia de la reincidencia' },
  { id: 'caso_002', title: 'Demora en la visita', customer: 'Cliente de demostración', category: 'Puntualidad', status: 'Abierta', priority: 'Media', detail: 'Se recibió una valoración baja de puntualidad en Palermo.', next: 'Revisar la comunicación y el horario acordado' }
]
export function CasesPage({ warranty = false }: { warranty?: boolean }) {
  const rows = warranty ? cases.filter(item => item.category === 'Garantía') : cases
  const [id, setId] = useState(rows[0].id)
  const selected = rows.find(item => item.id === id)!
  return <><Header title={warranty ? 'Garantías' : 'Reclamos'} description={warranty ? 'Revisá la elegibilidad, la evidencia y el seguimiento de cada garantía.' : 'Una cola clara para escuchar al cliente y resolver con contexto.'} section="Confianza y calidad" /><Metrics items={[{ label: 'Casos disponibles', value: rows.length, detail: 'Registros demostrativos' }, { label: 'En revisión', value: 1, detail: 'Reincidencia a las 48 horas' }, { label: 'Resueltos', value: 0, detail: 'En la muestra actual' }, { label: 'SLA', value: 'Sin datos', detail: 'Falta la fecha de apertura' }]} /><DataTable title={warranty ? 'Garantías' : 'Reclamos'} rows={rows} search={r => [r.id, r.title, r.category]} filters={[{ label: 'Estado', value: r => r.status }]} columns={[{ key: 'id', label: 'Caso', render: r => <><strong>{r.id.toUpperCase()}</strong><small>{r.title}</small></> }, { key: 'type', label: 'Tipo', render: r => r.category }, { key: 'priority', label: 'Prioridad', render: r => <Badge value={r.priority} /> }, { key: 'status', label: 'Estado', render: r => <Badge value={r.status} /> }, { key: 'action', label: 'Acción', render: r => <Button aria-pressed={id === r.id} onClick={() => { setId(r.id); setTimeout(() => document.getElementById('case-review')?.scrollIntoView({ block: 'start', behavior: 'smooth' }), 0) }}>Revisar caso</Button> }]} /><div id="case-review" style={{ scrollMarginTop: 88 }}><CaseReview key={selected.id} item={selected} warranty={warranty} /></div></>
}
function CaseReview({ item, warranty }: { item: typeof cases[number]; warranty: boolean }) {
  const { draft, save } = useAdminDraft(`case-${item.id}`)
  const [decision, setDecision] = useState(draft?.decision ?? 'Solicitar información')
  const [note, setNote] = useState(draft?.note ?? '')
  const [saved, setSaved] = useState(false)
  return <div className="adm-two-col"><Panel title={item.title} description={item.id.toUpperCase()}><div className="adm-stack"><p>{item.detail}</p><Facts items={[["Estado registrado", <Badge key="status" value={item.status} />], ["Próximo paso", item.next], ["Evidencia", 'No adjuntada en la muestra']]} />{warranty && <Notice>Confirmá fecha de visita, alcance original y evidencia antes de aprobar o rechazar una garantía.</Notice>}</div></Panel><Panel title="Preparar seguimiento"><form onSubmit={event => { event.preventDefault(); save({ decision, note }); setSaved(true) }}><div className="adm-stack"><Field label="Próxima acción"><select value={decision} onChange={event => { setDecision(event.target.value); setSaved(false) }}><option>Solicitar información</option><option>Coordinar revisión técnica</option><option>Escalar a operaciones</option></select></Field><Field label="Nota interna"><textarea required value={note} onChange={event => { setNote(event.target.value); setSaved(false) }} placeholder="Contexto, evidencia pendiente y responsable del seguimiento…" /></Field><Button variant="primary" type="submit">Guardar seguimiento de prueba</Button>{saved && <Notice success>Seguimiento guardado como borrador. No modifica el estado real del caso.</Notice>}</div></form></Panel></div>
}
export function AuditPage() {
  return <><Header title="Auditoría" description="Consultá qué ocurrió, quién intervino y sobre qué registro." section="Control y trazabilidad" /><Metrics items={[{ label: 'Eventos', value: auditLogs.length, detail: 'Disponibles en la muestra' }, { label: 'Informativos', value: 2, detail: 'Pago y asignación' }, { label: 'Requieren atención', value: 1, detail: 'Apertura de garantía' }, { label: 'Críticos', value: 0, detail: 'Sin eventos registrados' }]} /><DataTable title="Auditoría" rows={auditLogs} search={r => [r.id, r.actor, r.action, r.entity]} filters={[{ label: 'Severidad', value: r => r.severity }]} columns={[{ key: 'date', label: 'Fecha / evento', render: r => <><strong>{r.createdAt}</strong><small>{r.id.toUpperCase()}</small></> }, { key: 'actor', label: 'Actor', render: r => r.actor }, { key: 'action', label: 'Acción', render: r => <><strong>{r.action}</strong><small>{r.entity}</small></> }, { key: 'severity', label: 'Severidad', render: r => <Badge value={r.severity} /> }, { key: 'detail', label: 'Detalle', render: r => <details className="adm-detail-toggle"><summary>Ver contexto</summary><Facts items={[["Entidad", r.entity], ["Origen", r.actor], ["Valores anteriores", 'No disponibles']]} /></details> }]} /><Notice>Registro demostrativo de sólo lectura. No se incluyen datos anteriores/posteriores que no estén presentes en el evento.</Notice></>
}
