'use client'

import { useState } from 'react'
import { ArrowUpRight, ClipboardList, CreditCard, Users, Wrench } from 'lucide-react'
import { jobs, money, payments, professionals, qualityItems, requests } from '@/lib/mock/lysto-data'
import { ActionLink, Badge, Bars, Facts, Header, Metrics, Notice, Panel, Tabs } from './admin-ui'
import { zones } from './admin-model'

export function DashboardPage() {
  return <><Header title="Dashboard operativo" description="Lo que requiere atención, los trabajos en curso y la disponibilidad de tu red." action={<ActionLink primary href="/admin/solicitudes">Gestionar solicitudes <ArrowUpRight size={16} /></ActionLink>} /><Metrics items={[
    { label: 'Solicitudes por asignar', value: 2, detail: 'De 3 solicitudes registradas', icon: <ClipboardList /> }, { label: 'Trabajos activos', value: 1, detail: 'Un profesional en camino', icon: <Wrench />, tone: 'amber' }, { label: 'Profesionales aprobados', value: 2, detail: 'De 4 perfiles registrados', icon: <Users />, tone: 'green' }, { label: 'Pagos aprobados', value: money(43750), detail: 'Pendiente de captura', icon: <CreditCard />, tone: 'violet' }
  ]} /><div className="adm-two-col"><Panel title="Prioridades de la operación" description="Empezá por las solicitudes que necesitan una decisión." action={<Badge value="2 por asignar" />}>{requests.map(request => <div className="adm-list-item" key={request.id}><div><div className="adm-inline"><strong>{request.id.toUpperCase()}</strong><Badge value={request.status} /></div><p>{request.issueLabel} · {request.customer}</p><small>{request.address}</small></div><ActionLink href={`/admin/solicitudes/${request.id}`}>Revisar</ActionLink></div>)}</Panel><Panel title="Cobertura de la red" description="Profesionales aprobados por zona; muestra actual." action={<ActionLink href="/admin/zonas">Ver zonas</ActionLink>}><Bars items={zones.slice(0, 4).map(zone => ({ label: zone, value: professionals.filter(p => p.zone === zone && p.status === 'approved').length }))} /></Panel><Panel title="Actividad registrada" description="Volumen de la muestra por fecha, no métricas en tiempo real."><Bars items={['12/08/2026', '18/08/2026', '19/08/2026'].map(date => ({ label: date, value: requests.filter(r => r.createdAt.startsWith(date)).length + jobs.filter(j => j.scheduled === date).length, detail: `${requests.filter(r => r.createdAt.startsWith(date)).length} solicitudes · ${jobs.filter(j => j.scheduled === date).length} visitas` }))} /></Panel><Panel title="En resumen"><Facts items={[["Solicitudes prioritarias", 2], ["Esperando al cliente", 1], ["Rating de la red", '4,5 / 5'], ["Perfiles por validar", 1]]} /><div className="adm-inline" style={{ marginTop: 20 }}><ActionLink href="/admin/calidad">Revisar calidad</ActionLink><ActionLink href="/admin/reportes">Ver reportes</ActionLink></div></Panel></div></>
}
export function QualityPage() {
  return <><Header title="Calidad del servicio" description="Detectá los casos sensibles y acompañá cada resolución hasta el cierre." section="Confianza y calidad" action={<ActionLink primary href="/admin/reclamos">Gestionar reclamos</ActionLink>} /><Metrics items={[{ label: 'Señales de calidad', value: 3, detail: 'Casos demostrativos' }, { label: 'Garantías abiertas', value: 1, detail: 'Reincidencia informada' }, { label: 'Acciones correctivas', value: 1, detail: 'Puntualidad por revisar' }, { label: 'Profesionales destacados', value: 1, detail: 'Desempeño reconocido' }]} /><div className="adm-two-col"><Panel title="Cola prioritaria" description="Ordenada por necesidad de seguimiento.">{qualityItems.map((item, index) => <div className="adm-list-item" key={item.title}><div><strong>{item.title}</strong><p>{item.detail}</p><Badge value={item.status} /></div><ActionLink href={index === 0 ? '/admin/garantias' : index === 1 ? '/admin/reclamos' : '/admin/profesionales/pro_001'}>Revisar</ActionLink></div>)}</Panel><div className="adm-stack"><Panel title="Señales de la red"><Bars items={professionals.filter(p => p.status === 'approved').map(p => ({ label: p.name, value: p.rating, detail: `${p.rating} / 5` }))} /></Panel><Panel title="Criterios de atención"><Facts items={[["Reincidencia", 'Revisar garantía'], ["Disputa", 'Conservar evidencia'], ["Demora", 'Confirmar con ambas partes']]} /></Panel></div></div></>
}
export function ReportsPage() {
  const [period, setPeriod] = useState('Toda la muestra')
  const filteredPayments = payments.filter(p => period === 'Toda la muestra' || p.createdAt.startsWith('19/08/2026'))
  const filteredRequests = requests.filter(r => period === 'Toda la muestra' || r.createdAt.startsWith('19/08/2026'))
  const filteredJobs = jobs.filter(j => period === 'Toda la muestra' || j.scheduled === '19/08/2026')
  return <><Header title="Reportes" description="Una lectura clara del volumen, los ingresos y la calidad de la operación." section="Análisis" /><Tabs label="Período del reporte" value={period} onChange={setPeriod} options={['Toda la muestra', '19 de agosto']} /><Metrics items={[{ label: 'Solicitudes', value: filteredRequests.length, detail: 'Período seleccionado' }, { label: 'Trabajos', value: filteredJobs.length, detail: 'Visitas registradas' }, { label: 'Importe procesado', value: money(filteredPayments.reduce((s, p) => s + p.amount, 0)), detail: 'Aprobados y cobrados' }, { label: 'Comisión Lysto', value: money(filteredPayments.reduce((s, p) => s + p.platformFee, 0)), detail: 'No equivale a margen neto' }]} /><div className="adm-equal-col"><Panel title="Demanda por servicio"><Bars items={filteredRequests.map(r => ({ label: r.issueLabel, value: 1, detail: money(r.price) }))} /></Panel><Panel title="Estado de las solicitudes"><Bars items={[{ label: 'Por asignar', value: filteredRequests.filter(r => r.status === 'pending_assignment').length }, { label: 'Pago aprobado', value: filteredRequests.filter(r => r.status === 'payment_approved').length }, { label: 'Pendiente de pago', value: filteredRequests.filter(r => r.status === 'pending_payment').length }]} /></Panel><Panel title="Aceptación de profesionales"><Bars items={professionals.map(p => ({ label: p.name, value: p.acceptanceRate * 100, detail: `${Math.round(p.acceptanceRate * 100)}%` }))} /></Panel><Panel title="Qué falta para medir mejor"><Facts items={[["Conversión", 'Cohortes completas'], ["Tiempo de asignación", 'Timestamps de eventos'], ["Recompra", 'Historial unificado'], ["Margen neto", 'Costos y devoluciones']]} /></Panel></div><Notice>Los indicadores se calculan sobre los registros disponibles. Esta muestra no permite inferir tendencias ni comparar períodos de negocio.</Notice></>
}
