'use client'

import Link from 'next/link'
import { useState } from 'react'
import { CheckCircle2, MapPin, Star } from 'lucide-react'
import { customers, equipment, jobs, money, payments, professionals, requests, type CustomerRecord, type JobRecord, type ProfessionalRecord, type ServiceRequestRecord } from '@/lib/mock/lysto-data'
import { ActionLink, Badge, Button, Checklist, Facts, Field, Header, Metrics, Notice, Panel, Person, useAdminDraft } from './admin-ui'
import { JobTable, RequestTable } from './admin-lists'

function CustomerPanel({ name }: { name: string }) {
  const customer = customers.find(c => c.name === name)
  return <Panel title="Cliente"><div className="adm-stack"><Person name={name} detail={customer?.email} />{customer && <><Facts items={[["Teléfono", customer.phone], ["Domicilio", customer.address], ["Servicios históricos", customer.jobsCount]]} /><ActionLink href={`/admin/clientes/${customer.id}`}>Ver ficha del cliente</ActionLink></>}</div></Panel>
}
export function CandidateSelector({ request }: { request: ServiceRequestRecord }) {
  const { draft, save } = useAdminDraft(`matching-${request.id}`)
  const [selected, setSelected] = useState(draft?.professional ?? '')
  const [message, setMessage] = useState('')
  const candidates = professionals.filter(p => p.status === 'approved').sort((a, b) => b.score - a.score)
  const canAssign = ['pending_assignment', 'payment_approved'].includes(request.status)
  return <Panel title="Profesionales sugeridos" description="Ranking demostrativo por score. Confirmá zona, disponibilidad y herramientas antes de asignar.">
    {candidates.map((professional, index) => <div className={`adm-candidate ${selected === professional.id ? 'selected' : ''}`} key={professional.id}><label><input type="radio" name={`candidate-${request.id}`} value={professional.id} checked={selected === professional.id} onChange={() => { setSelected(professional.id); setMessage('') }} /><Person name={professional.name} detail={`${index === 0 ? 'Mayor score' : 'Alternativa'} · ${professional.zone}`} /></label><Facts items={[["Score", `${professional.score} / 100`], ["Calificación", `${professional.rating} / 5`], ["Disponibilidad informada", professional.nextAvailability], ["Herramientas", `${professional.tools.length} declaradas`]]} /><Link href={`/admin/profesionales/${professional.id}`} className="adm-button adm-button-quiet">Ver perfil y documentación</Link></div>)}
    {!canAssign && <Notice>La solicitud está pendiente de pago. La asignación permanece bloqueada hasta su aprobación.</Notice>}
    <div className="adm-save-bar"><p>Se prepara una selección interna; no se notifica al profesional.</p><Button variant="primary" disabled={!selected || !canAssign} onClick={() => { save({ professional: selected }); setMessage('Selección guardada como borrador de esta sesión. No se realizó una asignación real.') }}>Guardar selección</Button></div>{message && <Notice success>{message}</Notice>}
  </Panel>
}
export function MatchingPage() {
  const [id, setId] = useState(requests[0].id)
  const request = requests.find(r => r.id === id)!
  return <><Header title="Matching de profesionales" description="La persona adecuada para cada servicio, con criterios visibles y una decisión informada." /><div className="adm-two-col adm-matching-layout"><div className="adm-stack"><Panel title="Solicitud a asignar"><div className="adm-stack"><Field label="Seleccionar solicitud"><select value={id} onChange={event => setId(event.target.value)}>{requests.map(r => <option key={r.id} value={r.id}>{r.id.toUpperCase()} · {r.customer}</option>)}</select></Field><Badge value={request.status} /><h2>{request.issueLabel}</h2><Facts items={[["Cliente", request.customer], ["Dirección", request.address], ["Horario", request.timeWindow], ["Importe", money(request.price)], ["Prioridad", <Badge key="priority" value={request.urgency} />]]} /><ActionLink href={`/admin/solicitudes/${request.id}`}>Ver diagnóstico completo</ActionLink></div></Panel><Notice>La recomendación usa perfiles demostrativos. El score no garantiza compatibilidad técnica ni disponibilidad en tiempo real.</Notice></div><CandidateSelector key={id} request={request} /></div></>
}
export function RequestDetailPage({ request }: { request: ServiceRequestRecord }) {
  return <><Header title={`Solicitud ${request.id.toUpperCase()}`} description={`${request.issueLabel} · Creada el ${request.createdAt}`} back={{ label: 'Solicitudes', href: '/admin/solicitudes' }} action={<Badge value={request.status} />} /><div className="adm-two-col"><div className="adm-stack"><Panel title="Diagnóstico inicial" description="Orientativo. El diagnóstico definitivo se realiza durante la visita."><div className="adm-stack"><h2>{request.issueLabel}</h2><p>{request.diagnosis}</p><Facts items={[["Servicio", 'Aire acondicionado'], ["Inmueble", request.property], ["Material adjunto", `${request.mediaCount} archivos declarados`]]} /><Notice>Los archivos adjuntos no están disponibles en esta muestra.</Notice></div></Panel><Panel title="Precio y alcance"><Facts items={[["Importe de la solicitud", money(request.price)], ["Modalidad", <Badge key="urgency" value={request.urgency} />], ["Franja solicitada", request.timeWindow]]} /><p style={{ marginTop: 16, color: '#64748b' }}>Los materiales y tareas adicionales requieren validación antes de ejecutarse.</p></Panel><CandidateSelector request={request} /></div><div className="adm-stack"><CustomerPanel name={request.customer} /><Panel title="Dónde y cuándo"><div className="adm-stack"><div className="adm-inline"><MapPin size={18} /><strong>{request.address}</strong></div><Facts items={[["Horario", request.timeWindow], ["Acceso", request.property]]} /></div></Panel><Panel title="Actividad disponible"><div className="adm-timeline"><div><small>{request.createdAt}</small><strong>Solicitud registrada</strong><p>{request.issueLabel}</p></div><div><strong>Estado actual</strong><p><Badge value={request.status} /></p></div></div></Panel></div></div></>
}
export function JobDetailPage({ job }: { job: JobRecord }) {
  const professional = professionals.find(p => p.name === job.professional)
  const payment = payments.find(p => p.jobId === job.id)
  const [expanded, setExpanded] = useState(false)
  const isCompleted = job.status.startsWith('completed')
  return <><Header title={`Trabajo ${job.id.toUpperCase()}`} description={`${job.issueLabel} · ${job.scheduled} · ${job.timeWindow}`} back={{ label: 'Trabajos', href: '/admin/trabajos' }} action={<Badge value={job.status} />} /><Panel title="Seguimiento del servicio"><div className="adm-stepper">{['Confirmado', 'En camino', 'En el domicilio', 'Finalizado'].map((step, index) => <div key={step} className={isCompleted || index < 2 ? 'active' : ''}><strong>{index + 1}. {step}</strong><small>{index === (isCompleted ? 3 : 1) ? 'Estado registrado' : ''}</small></div>)}</div></Panel><div className="adm-two-col"><div className="adm-stack"><Panel title="Resumen del trabajo"><Facts items={[["Servicio", job.issueLabel], ["Equipo", job.equipment], ["Dirección", job.address], ["Próximo paso", job.nextStep]]} /></Panel><Panel title="Checklist de revisión" description="Ayuda de revisión local. No modifica el checklist real del profesional."><Checklist items={['Revisar el diagnóstico y alcance acordado', 'Confirmar evidencia de la intervención', 'Verificar el importe y estado del pago', 'Comprobar la conformidad del cliente']} /></Panel><Panel title="Actividad del trabajo"><div className="adm-timeline"><div><small>{job.scheduled} · {job.timeWindow}</small><strong>Visita programada</strong><p>{job.professional}</p></div><div><strong>Último estado disponible</strong><p><Badge value={job.status} /></p><p>{job.nextStep}</p></div></div></Panel><Panel title="Acciones administrativas"><div className="adm-stack"><div className="adm-inline"><ActionLink href="/admin/reclamos">Revisar reclamos</ActionLink><ActionLink href="/admin/garantias">Revisar garantías</ActionLink><Button onClick={() => setExpanded(!expanded)} aria-expanded={expanded}>Otras acciones</Button></div>{expanded && <Notice>Reasignar, cancelar o devolver dinero requiere conexión al sistema real y confirmación de permisos. Estas operaciones no están habilitadas en la demostración.</Notice>}</div></Panel></div><div className="adm-stack"><Panel title="Profesional asignado"><div className="adm-stack"><Person name={job.professional} detail={professional?.specialty} />{professional && <><Facts items={[["Calificación", `${professional.rating} / 5`], ["Teléfono", professional.phone]]} /><ActionLink href={`/admin/profesionales/${professional.id}`}>Ver perfil</ActionLink></>}</div></Panel><Panel title="Detalle del pago"><div className="adm-stack"><div className="adm-money">{money(job.amount)}</div><Badge value={job.paymentStatus} />{payment && <Facts items={[["Comisión Lysto", money(payment.platformFee)], ["Profesional", money(payment.professionalAmount)], ["Medio", 'Mercado Pago']]} />}<ActionLink href="/admin/pagos">Ver pagos</ActionLink></div></Panel><CustomerPanel name={job.customer} /></div></div></>
}
export function ProfessionalDetailPage({ professional: p }: { professional: ProfessionalRecord }) {
  return <><Header title="Perfil profesional" description="Documentación, capacidad técnica e historial para tomar mejores decisiones." back={{ label: 'Profesionales', href: '/admin/profesionales' }} action={<Badge value={p.status} />} /><Panel title="Información del perfil"><div className="adm-profile"><Person name={p.name} detail={p.specialty} /></div></Panel><Metrics items={[{ label: 'Score Lysto', value: `${p.score}/100`, detail: 'Señal de desempeño' }, { label: 'Calificación', value: p.rating, detail: 'Sobre 5 puntos', icon: <Star /> }, { label: 'Trabajos realizados', value: p.jobsCompleted, detail: 'Total declarado' }, { label: 'Aceptación', value: `${Math.round(p.acceptanceRate * 100)}%`, detail: 'Solicitudes recibidas' }]} /><div className="adm-two-col"><div className="adm-stack"><Panel title="Documentación y habilitación"><Facts items={[["Estado", <Badge key="status" value={p.status} />], ["Matrícula declarada", p.hasLicense ? 'Sí' : 'No'], ["Movilidad", p.mobility], ["Contacto", p.email]]} /><Notice>Esta ficha contiene un resumen. No se adjuntaron documentos verificables en la muestra.</Notice></Panel><Panel title="Herramientas declaradas"><div className="adm-checklist">{p.tools.map(tool => <div className="adm-inline" style={{ minHeight: 40 }} key={tool}><CheckCircle2 color="#178351" size={18} />{tool}</div>)}</div></Panel></div><div className="adm-stack"><Panel title="Zona y disponibilidad"><Facts items={[["Cobertura", p.zone], ["Próximo horario", p.nextAvailability], ["Teléfono", p.phone]]} /></Panel><Panel title="Mercado Pago"><div className="adm-stack"><Badge value={p.mercadoPago} /><p>La conexión permite recibir el monto correspondiente a los servicios.</p><ActionLink href="/admin/marketplace">Consultar reglas</ActionLink></div></Panel></div></div><h2>Trabajos disponibles en la muestra</h2><JobTable rows={jobs.filter(job => job.professional === p.name)} /></>
}
export function CustomerDetailPage({ customer: c }: { customer: CustomerRecord }) {
  const customerEquipment = equipment.filter(e => e.customer === c.name)
  return <><Header title={c.name} description={`Ficha del cliente · ${c.id.toUpperCase()}`} back={{ label: 'Clientes', href: '/admin/clientes' }} action={<Badge value={c.risk} />} /><div className="adm-two-col"><div className="adm-stack"><Panel title="Equipos del cliente" description="Equipos disponibles en la muestra técnica.">{customerEquipment.length ? customerEquipment.map(item => <div className="adm-list-item" key={item.id}><div><strong>{item.nickname}</strong><p>{item.brand} · {item.model}</p><small>Próximo mantenimiento: {item.nextMaintenance}</small></div></div>) : <Notice>No hay equipos de este cliente cargados en la muestra, aunque su ficha declara {c.equipmentCount}.</Notice>}<div style={{ marginTop: 16 }}><ActionLink href="/admin/equipos">Abrir base técnica</ActionLink></div></Panel><Panel title="Relación con Lysto"><Facts items={[["Servicios históricos declarados", c.jobsCount], ["Último servicio en ficha", c.lastService], ["Equipos declarados", c.equipmentCount]]} /></Panel></div><Panel title="Datos de contacto"><div className="adm-stack"><Person name={c.name} detail={c.email} /><Facts items={[["Teléfono", c.phone], ["Domicilio", c.address], ["Segmento", <Badge key="risk" value={c.risk} />]]} /></div></Panel></div><h2>Solicitudes de {c.name.split(' ')[0]}</h2><RequestTable rows={requests.filter(r => r.customer === c.name)} /><h2>Trabajos disponibles</h2><JobTable rows={jobs.filter(j => j.customer === c.name)} /></>
}
